### ISSUE TITLE
NPE in Pipe.isObsolete (Pipe.java:103)

### ISSUE THREAD

**Issue by dmoore247** [tap-git/tap#4]
File: /X/tn/input/event/20111111 exists and is up to date.
Will run mapper X.mapreduce.jobs.LoadEvent$Mapper reading /X/tn/input/event/20111111 reducer X.mapreduce.jobs.LoadEvent$Reducer, producing:
  /X/tn/tmp/tk/20111111: obsolete
Submitting job:
map: X.mapreduce.jobs.LoadEvent$Mapper
reduce: X.mapreduce.jobs.LoadEvent$Reducer
reading: /X/tn/input/event/20111111
writing: /X/tn/tmp/tk/20111111
group by:hour
Exception in thread "main" java.lang.NullPointerException
        at tap.core.Pipe.isObsolete(Pipe.java:103)
        at tap.core.Tap.generatePlan(Tap.java:193)
        at tap.core.Tap.execute(Tap.java:97)
        at sidebar.mapreduce.jobs.LoadEvent.run(LoadEvent.java:53)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
        at X.mapreduce.jobs.LoadEvent.main(LoadEvent.java:121)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:156)
File: /X/tn/input/event/20111111 exists and is up to date.

**Comment by dmoore247** [comment]
Pipe.java
101:            if (fs.exists(dfsPath)) {
102:                FileStatus[] statuses = fs.listStatus(dfsPath);
103:                for (FileStatus status : statuses) {
104:                    if (!status.isDir()) {

Looks like fs.listStatus(dfsPath) returned a null.
