### ISSUE TITLE
NPE in Pipe.clearAndPrepareOutput(Pipe.java:137)

### ISSUE THREAD

**Issue by dmoore247** [tap-git/tap#5]
env HADOOP_CLASS_PATH=jackson-core-asl-1.9.3.jar:jackson-mapper-asl-1.9.3.jar hadoop jar /shared/build/TBA/java/X/target/X-1.0-SNAPSHOT.jar X.mapreduce.jobs.LoadItem -i /sidebar/tn/input/ulog/20111111 -o /X/tn/tmp/item/20111111env HADOOP_CLASS_PATH=jackson-core-asl-1.9.3.jar:jackson-mapper-asl-1.9.3.jar hadoop jar /shared/build/TBA/java/X/target/X-1.0-SNAPSHOT.jar X.mapreduce.jobs.LoadItem -i /X/tn/input/ulog/20111111 -o /X/tn/tmp/item/20111111env HADOOP_CLASS_PATH=jackson-core-asl-1.9.3.jar:jackson-mapper-asl-1.9.3.jar hadoop jar /shared/build/TBA/java/X/target/X-1.0-SNAPSHOT.jar X.mapreduce.jobs.LoadItem -i /X/tn/input/ulog/20111111 -o /X/tn/tmp/item/20111111env HADOOP_CLASS_PATH=jackson-core-asl-1.9.3.jar:jackson-mapper-asl-1.9.3.jar hadoop jar /shared/build/TBA/java/sidebar/target/X-1.0-SNAPSHOT.jar sidebar.mapreduce.jobs.LoadItem -i /sidebar/tn/input/ulog/20111111 -o /X/tn/tmp/item/20111111Job failure
java.lang.NullPointerException
        at tap.core.Pipe.clearAndPrepareOutput(Pipe.java:137)
        at tap.core.Phase.submit(Phase.java:743)
        at tap.core.Tap$1.run(Tap.java:149)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:662)

**Comment by dmoore247** [comment]
The context of this is that we were re-running a job targeting directories that already existed.

**Comment by dmoore247** [comment]
Similar to Issue #4

135:            if (fs.exists(dfsPath)) {
136:                FileStatus[] statuses = fs.listStatus(dfsPath);
137:                for (FileStatus status : statuses) {
138:                    if (status.isDir()) {
